### ISSUE TITLE
Is the "Re-scale orientation to [-pi/2 to +pi/2]" code available?

### ISSUE THREAD

**Issue by sume-cn** [mherb/kalman#32]
In examples/Robot1/SystemModel.hpp
as the title says

**Comment by sume-cn** [comment]
And, should this be done in transition function(may cause discontinuity) or measurement ?

**Comment by mherb** [comment]
Actually this is currently not done in the implementation as far as I can see (despite the comment that you mentioned). This issue is however important in real applications and there is a plan to add proper support for such manifold state spaces (see #18), which however will likely not be implemented in the near future by myself.

**Comment by sume-cn** [comment]
thank you, it's very helpful.
