### ISSUE TITLE
Is this repo still maintained now?

### ISSUE THREAD

**Issue by neozhaoliang** [mherb/kalman#33]
I'm thinking of adding RTS backward filters to this project, but I'm wondering if it still accepts PRS?

**Comment by mherb** [comment]
Dear @neozhaoliang, unfortunately there is no active development at the moment because I am mostly busy with other projects. However, PRs are certainly considered for merging and are in any case helpful for others looking for the same functionality (I guess you are talking about Rauch–Tung–Striebel smoother, right?)

**Comment by neozhaoliang** [comment]
Yes I mean the Rauch–Tung–Striebel filter. 

The repo has not been update for years, are there any requirements of expected PRs like coding styles?

**Comment by mherb** [comment]
Unofrtunately there is not a particular defined coding style as of now, but aligning new code with the style of the existing code is certainly a good idea.
